name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet PinGod.VP.csproj restore
    - name: Build
      run: dotnet build PinGod.VP.csproj --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -r win-x86 PinGod.VP.csproj -o "/home/runner/work/PinGod.VP/PinGod.VP/builds/PinGod.VP-x86" | 7z a -tzip "${release_name}.zip" "/home/runner/work/PinGod.VP/PinGod.VP/builds/PinGod.VP-x86*"       
