name: .NET 472

on:
  push:
    branches: [ master, develop/add_switch_memory_mapping]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: NuGet/setup-nuget@v1.0.2
    - name: Restore dependencies
      run: nuget restore PinGod.VP.sln
    - name: Build
      run: msbuild PinGod.VP.sln /p:Configuration=Release /p:DeployOnBuild=true /p:Platform=x86
    - name: Build Artifact x86
      uses: actions/upload-artifact@v2
      with:
        name: PinGod.VP
        path: D:\a\PinGod.VP\PinGod.VP\PinGod.VP\bin\x86\Release
