name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore "PinGod.VP/PinGod.VP.csproj"
    - name: Build
      run: dotnet build  "PinGod.VP/PinGod.VP.csproj" --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -r win-x86 "PinGod.VP/PinGod.VP.csproj"
    - name: Build Artifact x86
      uses: actions/upload-artifact@v2
      with:
        name: PinGod.VP
        path: D:\a\PinGod.VP\PinGod.VP\PinGod.VP\bin\Release\net5.0\win-x86\   
