name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore "PinGod.VP.csproj"
    - name: Build
      run: dotnet build  "PinGod.VP.csproj" --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -r win-x86 "PinGod.VP.csproj" 
    - name: Upload binaries to release  
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: D:\a\PinGod.VP\PinGod.VP\bin\Release\net5.0\win-x86\ 
        asset_name: PinGod.VP-x86.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Latest"        
      
