name: .NET 472

on:
  push:
    branches: [ master, develop/add_switch_memory_mapping]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout Code     

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
     
    - name: Restore NuGet Packages
      run: nuget restore PinGod.VP.sln
 
    - name: MSBUild
      working-directory: D:\a\PinGod.VP\PinGod.VP\
      run: msbuild PinGod.VP.sln /p:Configuration=Release /p:DeployOnBuild=true /p:Platform=x86

    - name: Build Artifact x86
      uses: actions/upload-artifact@v2
      with:
        name: PinGod.VP
        path: D:\a\PinGod.VP\PinGod.VP\build